matrix:
  include:
    - language: python
      python: 3.6.6
      before_script:
        - uname -a
        - cd analytics
        - pip install -r requirements.txt
        - sudo apt-get update
        - sudo apt-get install -y 
          apt-utils gnupg curl make g++ git
      script:
        - python -m unittest discover
notifications:
  email: false