version: '2.1'
services:
  server:
    image: hastic/server:latest
    build:
      dockerfile: server/Dockerfile
      context: .
    environment:
      HASTIC_API_KEY: ${HASTIC_API_KEY?"HASTIC_API_KEY variable is required"}
      GRAFANA_URL: ${GRAFANA_URL?"GRAFANA_URL variable is required"}

      HASTIC_ALERT_TYPE: ${HASTIC_ALERT_TYPE}
      HASTIC_ALERTMANAGER_URL: ${HASTIC_ALERTMANAGER_URL}
      HASTIC_WEBHOOK_URL: ${HASTIC_WEBHOOK_URL}
      HASTIC_INSTANCE_NAME: ${HASTIC_INSTANCE_NAME}
      HASTIC_ALERT_IMAGE: ${HASTIC_ALERT_IMAGE}
      HASTIC_DB_CONNECTION_STRING: ${HASTIC_DB_CONNECTION_STRING}
      HASTIC_DB_CONNECTION_TYPE: ${HASTIC_DB_CONNECTION_TYPE}
      HASTIC_TIMEZONE_OFFSET: ${HASTIC_TIMEZONE_OFFSET}

    ports:
      - ${HASTIC_PORT:-8000}:8000
    volumes:
      - data-volume:/var/www/data
    networks:
      - hastic-network
    restart: always

  analytics:
    image: hastic/analytics:latest
    build: analytics
    environment:
      # TODO: use any port for server connection
      HASTIC_SERVER_URL: "ws://server:8002"
      HS_AN_LOGGING_LEVEL: ${HS_AN_LOGGING_LEVEL}
    networks:
      - hastic-network
    restart: always

volumes:
  data-volume:

networks:
  hastic-network:
