version: '2.1'
services:
  server:
    image: hastic/server:latest
    build:
      dockerfile: server/Dockerfile
      context: .
    environment:
      ZMQ_CONNECTION_STRING: ${ZMQ_CONNECTION_STRING:-tcp://analytics:8002}
      HASTIC_API_KEY: ${HASTIC_API_KEY}
      HASTIC_WEBHOOK_URL: ${HASTIC_WEBHOOK_URL}
      HASTIC_WEBHOOK_TYPE: ${HASTIC_WEBHOOK_TYPE}
      GRAFANA_URL: ${GRAFANA_URL}
      HASTIC_INSTANCE_NAME: ${HASTIC_INSTANCE_NAME}
      HASTIC_WEBHOOK_IMAGE_ENABLED: ${HASTIC_WEBHOOK_IMAGE_ENABLED}
    ports:
      - ${HASTIC_PORT:-8000}:8000
    volumes:
      - data-volume:/var/www/data
    restart: always

  analytics:
    image: hastic/analytics:latest
    build: analytics
    restart: always
    command: ${HASTIC_ANALYTICS_COMMAND}
    #set HASTIC_ANALYTICS_COMMAND="python -um ptvsd --host 0.0.0.0 --port 5678 bin/server" for remote debug
    ports:
      - 5678:5678

volumes:
  data-volume:
