version: '2'
services:
  server:
    image: hastic/server:latest
    build: 
      dockerfile: server/Dockerfile
      context: .
    environment:
      HASTIC_API_KEY: ${HASTIC_API_KEY}
      ZMQ_CONNECTION_STRING: ${ZMQ_CONNECTION_STRING}
    ports:
      - 8000:8000
    volumes:
      - data-volume:/var/www/data
    restart: on-failure

  analytics:
    image: hastic/analytics:latest
    build: analytics
    restart: on-failure

volumes:
  data-volume:
